
/**
 * Action Types for Log In
 */
export const USER_LOG_IN_INITITATED = "USER_LOG_IN_INITITATED";
export const USER_LOG_IN_SUCCESS = "USER_LOG_IN_SUCCESS";
export const USER_LOG_IN_FAILED = "USER_LOG_IN_FAILED";

/**
 * Action Types for Planet Search
 */
export const PLANET_SEARCH_INITIATED = "PLANET_SEARCH_INITIATED";
export const PLANET_SEARCH_SUCCESS = "PLANET_SEARCH_SUCCESS";
export const PLANET_SEARCH_FAILED = "PLANET_SEARCH_FAILED";
